// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6fczswgAHD5kTHs6KeolSUbNRIUXPBiw',
    appId: '1:70998029741:web:5300c0127e297bc0821d24',
    messagingSenderId: '70998029741',
    projectId: 'aies-b9266',
    authDomain: 'aies-b9266.firebaseapp.com',
    storageBucket: 'aies-b9266.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALjxwhLYz05zOEm_9qbu5_LdbNbdxmyU8',
    appId: '1:70998029741:android:f31f4d91d59ace85821d24',
    messagingSenderId: '70998029741',
    projectId: 'aies-b9266',
    storageBucket: 'aies-b9266.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKLWXnsAjlgl3SljrDWudn8i1bTQ13ws',
    appId: '1:70998029741:ios:9b7f1a67a18054e9821d24',
    messagingSenderId: '70998029741',
    projectId: 'aies-b9266',
    storageBucket: 'aies-b9266.appspot.com',
    iosBundleId: 'com.mekongnet.aies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoKLWXnsAjlgl3SljrDWudn8i1bTQ13ws',
    appId: '1:70998029741:ios:dba7354f5645043d821d24',
    messagingSenderId: '70998029741',
    projectId: 'aies-b9266',
    storageBucket: 'aies-b9266.appspot.com',
    iosBundleId: 'com.mekongnet.ems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6fczswgAHD5kTHs6KeolSUbNRIUXPBiw',
    appId: '1:70998029741:web:2b71d4518c01df01821d24',
    messagingSenderId: '70998029741',
    projectId: 'aies-b9266',
    authDomain: 'aies-b9266.firebaseapp.com',
    storageBucket: 'aies-b9266.appspot.com',
  );

}