// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvNG-Pg0AuGnICFH3YffvwJvN20L30XUo',
    appId: '1:1037571020825:web:6294db510f0f97d97ff288',
    messagingSenderId: '1037571020825',
    projectId: 'aces-a0702',
    authDomain: 'aces-a0702.firebaseapp.com',
    storageBucket: 'aces-a0702.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNmXJjrSvZTJKYQS4YGU5rUEx0Xd_Gdo',
    appId: '1:1037571020825:android:4e6eeb9ad16a82687ff288',
    messagingSenderId: '1037571020825',
    projectId: 'aces-a0702',
    storageBucket: 'aces-a0702.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALlbY9FrqJVCuL2eP8qG6nMHFnNnUxbgY',
    appId: '1:1037571020825:ios:cd535e1d34a591537ff288',
    messagingSenderId: '1037571020825',
    projectId: 'aces-a0702',
    storageBucket: 'aces-a0702.appspot.com',
    iosBundleId: 'com.mekongnet.ems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALlbY9FrqJVCuL2eP8qG6nMHFnNnUxbgY',
    appId: '1:1037571020825:ios:cd535e1d34a591537ff288',
    messagingSenderId: '1037571020825',
    projectId: 'aces-a0702',
    storageBucket: 'aces-a0702.appspot.com',
    iosBundleId: 'com.mekongnet.ems',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvNG-Pg0AuGnICFH3YffvwJvN20L30XUo',
    appId: '1:1037571020825:web:0dd13ca45d95380b7ff288',
    messagingSenderId: '1037571020825',
    projectId: 'aces-a0702',
    authDomain: 'aces-a0702.firebaseapp.com',
    storageBucket: 'aces-a0702.appspot.com',
  );

}